// Generated by gencpp from file kuka_kinematics/SolvePositionIKResponse.msg
// DO NOT EDIT!


#ifndef KUKA_KINEMATICS_MESSAGE_SOLVEPOSITIONIKRESPONSE_H
#define KUKA_KINEMATICS_MESSAGE_SOLVEPOSITIONIKRESPONSE_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <sensor_msgs/JointState.h>

namespace kuka_kinematics
{
template <class ContainerAllocator>
struct SolvePositionIKResponse_
{
  typedef SolvePositionIKResponse_<ContainerAllocator> Type;

  SolvePositionIKResponse_()
    : joints()
    , isValid(false)
    , result_type(0)  {
    }
  SolvePositionIKResponse_(const ContainerAllocator& _alloc)
    : joints(_alloc)
    , isValid(false)
    , result_type(0)  {
  (void)_alloc;
    }



   typedef  ::sensor_msgs::JointState_<ContainerAllocator>  _joints_type;
  _joints_type joints;

   typedef uint8_t _isValid_type;
  _isValid_type isValid;

   typedef uint8_t _result_type_type;
  _result_type_type result_type;



// reducing the odds to have name collisions with Windows.h 
#if defined(_WIN32) && defined(RESULT_INVALID)
  #undef RESULT_INVALID
#endif

  enum {
    RESULT_INVALID = 0u,
  };


  typedef boost::shared_ptr< ::kuka_kinematics::SolvePositionIKResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::kuka_kinematics::SolvePositionIKResponse_<ContainerAllocator> const> ConstPtr;

}; // struct SolvePositionIKResponse_

typedef ::kuka_kinematics::SolvePositionIKResponse_<std::allocator<void> > SolvePositionIKResponse;

typedef boost::shared_ptr< ::kuka_kinematics::SolvePositionIKResponse > SolvePositionIKResponsePtr;
typedef boost::shared_ptr< ::kuka_kinematics::SolvePositionIKResponse const> SolvePositionIKResponseConstPtr;

// constants requiring out of line definition

   



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::kuka_kinematics::SolvePositionIKResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::kuka_kinematics::SolvePositionIKResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::kuka_kinematics::SolvePositionIKResponse_<ContainerAllocator1> & lhs, const ::kuka_kinematics::SolvePositionIKResponse_<ContainerAllocator2> & rhs)
{
  return lhs.joints == rhs.joints &&
    lhs.isValid == rhs.isValid &&
    lhs.result_type == rhs.result_type;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::kuka_kinematics::SolvePositionIKResponse_<ContainerAllocator1> & lhs, const ::kuka_kinematics::SolvePositionIKResponse_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace kuka_kinematics

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::kuka_kinematics::SolvePositionIKResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::kuka_kinematics::SolvePositionIKResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::kuka_kinematics::SolvePositionIKResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::kuka_kinematics::SolvePositionIKResponse_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::kuka_kinematics::SolvePositionIKResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::kuka_kinematics::SolvePositionIKResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::kuka_kinematics::SolvePositionIKResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "c12d9f771bb138ce4b4650d1b2f8aa4f";
  }

  static const char* value(const ::kuka_kinematics::SolvePositionIKResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xc12d9f771bb138ceULL;
  static const uint64_t static_value2 = 0x4b4650d1b2f8aa4fULL;
};

template<class ContainerAllocator>
struct DataType< ::kuka_kinematics::SolvePositionIKResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "kuka_kinematics/SolvePositionIKResponse";
  }

  static const char* value(const ::kuka_kinematics::SolvePositionIKResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::kuka_kinematics::SolvePositionIKResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# joints[i]      == joint angle solution for each pose_state[i]\n"
"sensor_msgs/JointState joints\n"
"\n"
"# NOTE: isValid will be deprecated by result_type in future versions\n"
"bool isValid\n"
"\n"
"# result_type[i] == seed type used to find valid solution, joints[i];\n"
"# otherwise,     == RESULT_INVALID (no valid solution found).\n"
"uint8 RESULT_INVALID = 0\n"
"uint8 result_type\n"
"\n"
"\n"
"================================================================================\n"
"MSG: sensor_msgs/JointState\n"
"# This is a message that holds data to describe the state of a set of torque controlled joints. \n"
"#\n"
"# The state of each joint (revolute or prismatic) is defined by:\n"
"#  * the position of the joint (rad or m),\n"
"#  * the velocity of the joint (rad/s or m/s) and \n"
"#  * the effort that is applied in the joint (Nm or N).\n"
"#\n"
"# Each joint is uniquely identified by its name\n"
"# The header specifies the time at which the joint states were recorded. All the joint states\n"
"# in one message have to be recorded at the same time.\n"
"#\n"
"# This message consists of a multiple arrays, one for each part of the joint state. \n"
"# The goal is to make each of the fields optional. When e.g. your joints have no\n"
"# effort associated with them, you can leave the effort array empty. \n"
"#\n"
"# All arrays in this message should have the same size, or be empty.\n"
"# This is the only way to uniquely associate the joint name with the correct\n"
"# states.\n"
"\n"
"\n"
"Header header\n"
"\n"
"string[] name\n"
"float64[] position\n"
"float64[] velocity\n"
"float64[] effort\n"
"\n"
"================================================================================\n"
"MSG: std_msgs/Header\n"
"# Standard metadata for higher-level stamped data types.\n"
"# This is generally used to communicate timestamped data \n"
"# in a particular coordinate frame.\n"
"# \n"
"# sequence ID: consecutively increasing ID \n"
"uint32 seq\n"
"#Two-integer timestamp that is expressed as:\n"
"# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n"
"# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n"
"# time-handling sugar is provided by the client library\n"
"time stamp\n"
"#Frame this data is associated with\n"
"string frame_id\n"
;
  }

  static const char* value(const ::kuka_kinematics::SolvePositionIKResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::kuka_kinematics::SolvePositionIKResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.joints);
      stream.next(m.isValid);
      stream.next(m.result_type);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct SolvePositionIKResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::kuka_kinematics::SolvePositionIKResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::kuka_kinematics::SolvePositionIKResponse_<ContainerAllocator>& v)
  {
    s << indent << "joints: ";
    s << std::endl;
    Printer< ::sensor_msgs::JointState_<ContainerAllocator> >::stream(s, indent + "  ", v.joints);
    s << indent << "isValid: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.isValid);
    s << indent << "result_type: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.result_type);
  }
};

} // namespace message_operations
} // namespace ros

#endif // KUKA_KINEMATICS_MESSAGE_SOLVEPOSITIONIKRESPONSE_H
