// Generated by gencpp from file kuka_kinematics/SolvePositionIK.msg
// DO NOT EDIT!


#ifndef KUKA_KINEMATICS_MESSAGE_SOLVEPOSITIONIK_H
#define KUKA_KINEMATICS_MESSAGE_SOLVEPOSITIONIK_H

#include <ros/service_traits.h>


#include <kuka_kinematics/SolvePositionIKRequest.h>
#include <kuka_kinematics/SolvePositionIKResponse.h>


namespace kuka_kinematics
{

struct SolvePositionIK
{

typedef SolvePositionIKRequest Request;
typedef SolvePositionIKResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct SolvePositionIK
} // namespace kuka_kinematics


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::kuka_kinematics::SolvePositionIK > {
  static const char* value()
  {
    return "0b2822586a12e4c26260aa39340340f7";
  }

  static const char* value(const ::kuka_kinematics::SolvePositionIK&) { return value(); }
};

template<>
struct DataType< ::kuka_kinematics::SolvePositionIK > {
  static const char* value()
  {
    return "kuka_kinematics/SolvePositionIK";
  }

  static const char* value(const ::kuka_kinematics::SolvePositionIK&) { return value(); }
};


// service_traits::MD5Sum< ::kuka_kinematics::SolvePositionIKRequest> should match
// service_traits::MD5Sum< ::kuka_kinematics::SolvePositionIK >
template<>
struct MD5Sum< ::kuka_kinematics::SolvePositionIKRequest>
{
  static const char* value()
  {
    return MD5Sum< ::kuka_kinematics::SolvePositionIK >::value();
  }
  static const char* value(const ::kuka_kinematics::SolvePositionIKRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::kuka_kinematics::SolvePositionIKRequest> should match
// service_traits::DataType< ::kuka_kinematics::SolvePositionIK >
template<>
struct DataType< ::kuka_kinematics::SolvePositionIKRequest>
{
  static const char* value()
  {
    return DataType< ::kuka_kinematics::SolvePositionIK >::value();
  }
  static const char* value(const ::kuka_kinematics::SolvePositionIKRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::kuka_kinematics::SolvePositionIKResponse> should match
// service_traits::MD5Sum< ::kuka_kinematics::SolvePositionIK >
template<>
struct MD5Sum< ::kuka_kinematics::SolvePositionIKResponse>
{
  static const char* value()
  {
    return MD5Sum< ::kuka_kinematics::SolvePositionIK >::value();
  }
  static const char* value(const ::kuka_kinematics::SolvePositionIKResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::kuka_kinematics::SolvePositionIKResponse> should match
// service_traits::DataType< ::kuka_kinematics::SolvePositionIK >
template<>
struct DataType< ::kuka_kinematics::SolvePositionIKResponse>
{
  static const char* value()
  {
    return DataType< ::kuka_kinematics::SolvePositionIK >::value();
  }
  static const char* value(const ::kuka_kinematics::SolvePositionIKResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // KUKA_KINEMATICS_MESSAGE_SOLVEPOSITIONIK_H
